package com.cdg.buslinkbackend.model.entity;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.*;


@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Clients")
public class Client {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String ci;

    @DynamoDBAttribute
    private String full_name;

    @DynamoDBAttribute
    private String phone;

    @DynamoDBAttribute
    private String city;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String password;
    @DynamoDBAttribute
    private String role;

    @DynamoDBAttribute
    private boolean status;
}
