package com.cdg.buslinkbackend.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString
@DynamoDBTable( tableName = "Cooperatives")
public class Cooperative {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private Boolean status;

    @DynamoDBAttribute
    private String phone;

    @DynamoDBAttribute
    private String address;


    @DynamoDBAttribute
    private byte[] image;
}
