package com.cdg.buslinkbackend.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.cdg.buslinkbackend.model.enums.RoleType;

import lombok.*;

@Getter
@Setter
@AllArgsConstructor()
@NoArgsConstructor
@ToString
@Builder
@DynamoDBTable( tableName = "Roles")
public class Role {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private RoleType rol;

    public Role(RoleType rol){
        this.rol = rol;
    }


}
